import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Collection;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class Library {

    private Collection<Book> books;
    private PrintStream printStream;
    private BufferedReader bufferedReader;

    public Library(List<Book> listOfBooks, PrintStream printStream, BufferedReader bufferedReader) {
        this.books = listOfBooks;
        this.printStream = printStream;
        this.bufferedReader = bufferedReader;
    }

    public String open() {
        return "Welcome to the Library! Biblioteca is available!";
    }

    public void listAllBooks() {
        int bookIndex = 1;
        for (Book book : books) {
            printStream.println(bookIndex + ". " + book.toString());
            bookIndex++;
        }
    }


    public void checkoutBook() {
        printStream.println("Which book would you like to checkout?");
        String bookToCheckoutName = userBookSelection();
        Book bookToCheckout = null;
        for (Book book : books) {
            if (book.equalsName(bookToCheckoutName)) {
                bookToCheckout = book;
            }
        }
        if(bookToCheckout != null) {
            books.remove(bookToCheckout);
            printStream.println("Thank you! Enjoy the book");
        }
    }

    private String userBookSelection() {
        String input = "";
        try {
            input = bufferedReader.readLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return input;
    }
}
