import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Collection;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class Library {

    private List<Book> checkedOutBooks;
    private Collection<Book> books;
    private PrintStream printStream;
    private BufferedReader bufferedReader;

    public Library( List<Book> listOfBooks,List<Book> checkedOutBooks, PrintStream printStream, BufferedReader bufferedReader) {
        this.checkedOutBooks = checkedOutBooks;
        this.books = listOfBooks;
        this.printStream = printStream;
        this.bufferedReader = bufferedReader;
    }

    public String open() {
        return "Welcome to the Library! Biblioteca is available!";
    }

    public void listAllBooks() {
        printStream.println();
        for (Book book : books) {
            printStream.println(book.toString());
        }
        printStream.println();
    }


    public void checkoutBook() {
        printStream.println("Which book would you like to checkout?");
        String bookToCheckoutName = userBookSelection();
        Book bookToCheckout = findBookInList(bookToCheckoutName, books);
        if(bookToCheckout != null) {
            books.remove(bookToCheckout);
            checkedOutBooks.add(bookToCheckout);
            printStream.println("Thank you! Enjoy the book");
        }
        else {
            printStream.println("That book is not available.");
        }
    }

    private Book findBookInList(String bookToCheckoutName, Collection<Book> bookList) {
        Book bookToCheckout = null;
        for (Book book : bookList) {
            if (book.equalsName(bookToCheckoutName)) {
                bookToCheckout = book;
            }
        }
        return bookToCheckout;
    }

    private String userBookSelection() {
        String input = "";
        try {
            input = bufferedReader.readLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return input;
    }

    public void returnBook() {
        printStream.print("Enter the name of the book you want to return: ");
        String bookToReturnName = userBookSelection();
        Book bookToReturn = findBookInList(bookToReturnName,checkedOutBooks);
        if(bookToReturn != null){
            books.add(bookToReturn);
            checkedOutBooks.remove(bookToReturn);
            printStream.println("Thank you for returning the book.");
        }
        else {
            printStream.println("That is not a valid book to return.");
        }



    }
}
