import org.junit.Before;
import org.junit.Test;

import java.io.BufferedReader;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class LibraryTest {
    private Library library;
    private List<Book> listOfBooks;
    private PrintStream printStream;
    private BufferedReader bufferedReader;
    private List<Book> checkedOutBooks;

    @Before
    public void setup(){
        listOfBooks = new ArrayList<>();
        checkedOutBooks = new ArrayList<>();
        printStream = mock(PrintStream.class);
        bufferedReader = mock(BufferedReader.class);
        library = new Library(listOfBooks, checkedOutBooks, printStream, bufferedReader);
    }

    @Test
    public void shouldProduceWelcomeWhenOpen() {
        assertThat(library.open(), is("Welcome to the Library! Biblioteca is available!"));
    }

    @Test
    public void shouldListNothingWhenLibraryCreatedWithNoBooks(){
        verify(printStream, never()).println();
    }

    @Test
    public void shouldListAllBooksWhenLibraryCreatedWithBooks() {
        List<Book> listOfBooks = new ArrayList<>();
        Book book1 = mock(Book.class);
        when(book1.toString()).thenReturn("Book");
        listOfBooks.add(book1);
        Book book2 = mock(Book.class);
        when(book2.toString()).thenReturn("Book");
        listOfBooks.add(book2);
        Library library = new Library(listOfBooks, checkedOutBooks, printStream, bufferedReader);
        library.listAllBooks();
        verify(printStream, times(2)).println(anyString());
    }

    @Test
    public void shouldPrintLinesAboveAndBelowBooksWhenBooksAreListed() throws Exception {
        library.listAllBooks();
        verify(printStream, times(2)).println();
    }

    @Test
    public void shouldAskUserWhichBookWhenUserSaysToCheckoutBook() throws Exception {
        library.checkoutBook();
        verify(printStream).println("Which book would you like to checkout?");
    }


    @Test
    public void shouldUpdateLibraryWhenUserChecksOutBook() throws Exception {
        Book book = mock(Book.class);
        when(book.equalsName("Book")).thenReturn(true);
        when(bufferedReader.readLine()).thenReturn("Book");
        listOfBooks.add(book);

        library.checkoutBook();

        assertTrue(listOfBooks.isEmpty());
    }

    @Test
    public void shouldNotRemoveABookWhenTheBookIsNotInLibrary() throws Exception {
        Book book = mock(Book.class);
        when(book.equalsName("Book1")).thenReturn(false);
        when(bufferedReader.readLine()).thenReturn("Book1");
        listOfBooks.add(book);

        library.checkoutBook();

        assertFalse(listOfBooks.isEmpty());

    }

    @Test
    public void shouldTellUserToEnjoyBookWhenBookSuccessfullyCheckedOut() throws Exception {
        Book book = mock(Book.class);
        when(book.equalsName("Book")).thenReturn(true);
        when(bufferedReader.readLine()).thenReturn("Book");
        listOfBooks.add(book);

        library.checkoutBook();

        verify(printStream).println("Thank you! Enjoy the book");
    }

    @Test
    public void shouldNotTellUserToEnjoyBookWhenBookIsNotSuccessfullyCheckedOut() throws Exception {
        Book book = mock(Book.class);
        when(book.equalsName("Book1")).thenReturn(false);
        when(bufferedReader.readLine()).thenReturn("Book1");
        listOfBooks.add(book);

        library.checkoutBook();

        verify(printStream, never()).println("Thank you! Enjoy the book");
    }

    @Test
    public void shouldNotifyOfUnsuccessfulCheckoutWhenBookIsNotSuccessfullyCheckedOut() throws Exception {
        Book book = mock(Book.class);
        when(book.equalsName("Book1")).thenReturn(false);
        when(bufferedReader.readLine()).thenReturn("Book1");
        listOfBooks.add(book);

        library.checkoutBook();

        verify(printStream).println("That book is not available.");
    }

    @Test
    public void shouldAddCheckedOutBookToCheckedOutBooksListWhenBookGetsCheckedOut() throws Exception {
        Book book = mock(Book.class);
        when(book.equalsName("Book")).thenReturn(true);
        when(bufferedReader.readLine()).thenReturn("Book");
        listOfBooks.add(book);
        library.checkoutBook();

        assertFalse(checkedOutBooks.isEmpty());



    }

    @Test
    public void shouldGetBookNameFromUserWhenUserReturnsABook() throws Exception {
        library.returnBook();

        verify(bufferedReader).readLine();
    }

    @Test
    public void shouldPromtUserToEnterBookNameWhenUserWantsToReturnABook() throws Exception {
        library.returnBook();

        verify(printStream).print("Enter the name of the book you want to return: ");
    }

    @Test
    public void shouldAddBookToListOfBooksWhenUserReturnsBookThatIsInCheckedOutBookList() throws Exception {
        Book book = mock(Book.class);
        when(bufferedReader.readLine()).thenReturn("Book");
        when(book.equalsName("Book")).thenReturn(true);

        checkedOutBooks.add(book);
        library.returnBook();
        assertFalse(listOfBooks.isEmpty());

    }


    @Test
    public void shouldNotAddBookToListOfBooksWhenUserReturnsBookThatIsNotInCheckedOutBookList() throws Exception {
        Book book = mock(Book.class);
        when(bufferedReader.readLine()).thenReturn("Book");
        when(book.equalsName("Book")).thenReturn(false);

        checkedOutBooks.add(book);
        library.returnBook();
        assertTrue(listOfBooks.isEmpty());

    }

    @Test
    public void shouldTellUserThankYouWhenBookSuccessfullyReturned() throws Exception {
        Book book = mock(Book.class);
        when(book.equalsName("Book")).thenReturn(true);
        when(bufferedReader.readLine()).thenReturn("Book");
        checkedOutBooks.add(book);

        library.returnBook();

        verify(printStream).println("Thank you for returning the book.");
    }

    @Test
    public void shouldNotifyOfUnsuccessfulReturnWhenBookIsNotSuccessfullyReturned() throws Exception {
        Book book = mock(Book.class);
        when(bufferedReader.readLine()).thenReturn("Book");
        when(book.equalsName("Book")).thenReturn(false);
        checkedOutBooks.add(mock(Book.class));

        library.returnBook();

        verify(printStream).println("That is not a valid book to return.");
    }



    //    @Test
//    public void shouldAddBookToLibraryWhenBookIsReturned() throws Exception {
//        library.returnBook();
//
//        assertFalse(listOfBooks.isEmpty());
//
//    }
}
